backend/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/',include('login.urls')),
    path('community/',include('community.urls')),
    path('profile/',include('profile_user.urls')),
    path('invitation/',include('invitation.urls')),
    path('report/',include('report.urls')),
    path('post/',include('post.urls')),
    path('notification/',include('notification.urls')),
    path('comment/',include('comment.urls')),
]

post/urls.py
from django.urls import path
from post.views import *

app_name = 'post'

urlpatterns = [
    path('<str:community_name>/<int:id>/', show_post_detail, name='show_post_detail'),
    path('<str:community_name>/create/', create_post, name='create_post'),
    path('<int:post_id>/like/', like_post, name='like_post'),
    path('<int:post_id>/dislike/', dislike_post, name='dislike_post'),
]

profile_user/urls.py
from django.urls import path
from profile_user.views import *

app_name = 'profile_user'

urlpatterns = [
    path('', index, name='index'),
    path('form_update/', show_form_update_profile, name='show_form_update_profile'),
    path('<str:username>/', get_profile_by_username, name='get_profile_by_username'),
    path('update/<str:username>/', update_profile, name='update_profile')
]

report/urls.py
from django.urls import path
from profile_user.views import *
from report.views import *

app_name = 'report'

urlpatterns = [
    # path('all_users/', all_users, name='all_users'),
    path('report_user/<int:reported_user_id>/', report_user, name='report_user'),
    path('view_reports/', view_reports, name='view_reports'),

]

profile_user/models.py
from django.db import models

# Create your models here.

profile_user/views.py
from django.http import JsonResponse
from django.shortcuts import redirect, render
from login.models import UserProfile
from django.contrib.auth.models import User
from report.models import Report
import json
from django.shortcuts import get_object_or_404
# Create your views here.
def index(request):
    return JsonResponse({"Message":"Hello this is from profile app"})

def show_form_update_profile(request):
    if request.user.is_authenticated:
        user = UserProfile.objects.get(user__username=request.user)
        print(user.get_data())
        context = {
            "bio": user.bio,    
        }
        return render(request, 'form_update_profile.html', context)
    else:
        return redirect('login:login_user')

def update_profile(request, username):
    if request.method == 'POST':
        data = json.loads(request.body)
        bio = data.get("bio")
        new_username = data.get("username")
        user_profile = UserProfile.objects.get(user__username=username)
        user_profile.bio = bio
        user_profile.save()
        try:
            user = User.objects.get(username=username)
            user.username = new_username
            user.save()
        except User.DoesNotExist:
            return JsonResponse({
                "Message": "User not found"
            })
        return JsonResponse({
            "redirect_url": f'/profile/{new_username}/'
        })
        return redirect('profile_user:get_profile_by_username', username=new_username)
    else:
        return redirect('profile_user:show_form_update_profile')


def get_profile_by_username(request, username):
    # Fetch the requested user's profile
    print(request.user)
    report_success = request.GET.get('report_success') == 'True'
    print(report_success)
    if not request.user.is_authenticated:
        return redirect('login:login_user')
    
    user = get_object_or_404(UserProfile, user__username=username)

    print(user.get_data()['username'])
    # Fetch the logged-in user
    logged_in_user = request.user
    
    # Check if the logged-in user has already reported this profile
    already_reported = Report.objects.filter(reported_user=user.user, reporter=logged_in_user).exists()
    
    context = {
        "this_user": user.get_data(),
        "username": user.get_data()['username'],
        "role": user.role,
        "bio": user.bio,
        "already_reported": already_reported,
        "report_success" : report_success
    }

    print(user.get_data())

    return render(request, 'profile.html', context)

profile_user/templates/form_update_profile.html
{% extends 'base.html' %} {% load static %} {% block meta %}
<title>Update Profile</title>
<style>
	#updateButton.loading {
		cursor: not-allowed;
		opacity: 0.7;
	}
</style>
<script>
	function updateProfile(event) {
		event.preventDefault();
		const updateButton = document.getElementById("updateButton");
		updateButton.disabled = true; // Disable the button to prevent multiple submissions
		updateButton.classList.add("loading"); // Add loading class to the button
		const username = document.getElementById("username").value;
		const bio = document.getElementById("bio").value;
		const updatePath = "/profile/update/{{user.username}}/";
		fetch(updatePath, {
			method: "POST",
			headers: {
				"Content-Type": "application/json",
			},
			body: JSON.stringify({ username, bio }),
		})
			.then((response) => response.json())
			.then((data) => {
				console.log(data);
				if (data.message) {
					showAlert("User not found!", "error");
				} else if (data.redirect_url) {
					showAlert("Update profile success!", "success");
					window.location.href = data.redirect_url;
				}
			})
			.catch((error) => {
				console.error("Error:", error);
				showAlert("An error occurred during the update", "error");
			})
			.finally(() => {
				updateButton.disabled = false; // Enable the button after the request is complete
				updateButton.classList.remove("loading"); // Remove loading class
			});
	}
	function showAlert(message, type) {
		Toastify({
			text: message,
			duration: 3000,
			gravity: "bottom",
			position: "right",
			backgroundColor: type === "success" ? "#4CAF50" : "#F44336",
		}).showToast();
	}
</script>
{% endblock meta %} {% block content %}
<div class="min-h-screen flex flex-col items-center p-10">
	<a href="/profile/{{user.username}}" class="flex items-center mb-4 text-blue-500 hover:text-blue-700">
		<i class="fa fa-angle-double-left" style="font-size: 24px"></i>
		<p class="text-sm">&nbspBack</p>
	</a>

	<form onsubmit="updateProfile(event)" class="max-w-md w-full">
		<div class="bg-white p-6 rounded-lg shadow-md mb-6">
			<h1 class="text-3xl font-bold mb-5">Update My Profile</h1>

			<div class="mb-4">
				<label for="username" class="block text-gray-700 text-sm font-bold mb-2">Username</label>
				<input
					id="username"
					type="text"
					placeholder="Username"
					value="{{user.username}}"
					required
					class="w-full px-4 py-2 rounded-md border-2 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
				/>
			</div>

			<div class="mb-4">
				<label for="bio" class="block text-gray-700 text-sm font-bold mb-2">Bio</label>
				<textarea
					id="bio"
					placeholder="Bio"
					required
					class="w-full rounded border-2 py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
				>
{{bio}}</textarea
				>
			</div>

			<button
				id="updateButton"
				type="submit"
				class="w-full px-4 py-2 rounded-md bg-blue-500 hover:bg-blue-700 text-white"
			>
				Update Profile
			</button>
		</div>
	</form>
</div>

{% endblock content %}

profile_user/templates/profile.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<title>{{ username }} - Profile</title>
{% endblock meta %}
{% block content %}
<div class="h-screen flex flex-col items-center p-10">
    {% if request.user.username == username %}
        <div class="bg-gray-200 p-6 rounded-lg shadow-md mb-6">
            <div class="flex items-center mb-4">
                <svg
                    class="w-8 h-8 mr-2 text-blue-500"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                    xmlns="http://www.w3.org/2000/svg"
                >
                    <path
                        stroke-linecap="round"
                        stroke-linejoin="round"
                        stroke-width="2"
                        d="M12 21v-2M12 3v-2M4 12h2M18 12h2M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
                    ></path>
                </svg>

                <h1 class="text-3xl font-bold">Hello, {{ username }}!</h1>
            </div>
            <div class="text-lg">
                <p><strong>Role:</strong> {{ role }}</p>
                <p><strong>Bio:</strong> {{ bio }}</p>
            </div>
        </div>
    {% else %}
		<div class="bg-gray-200 p-6 rounded-lg shadow-md mb-6">
			<div class="flex items-center mb-4">
				<svg
					class="w-8 h-8 mr-2 text-blue-500"
					fill="none"
					stroke="currentColor"
					viewBox="0 0 24 24"
					xmlns="http://www.w3.org/2000/svg"
				>
					<path
						stroke-linecap="round"
						stroke-linejoin="round"
						stroke-width="2"
						d="M12 21v-2M12 3v-2M4 12h2M18 12h2M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
					></path>
				</svg>

				<h1 class="text-3xl font-bold">It's {{ username }}'s profile!</h1>
			</div>
			<div class="text-lg">
				<p><strong>Role:</strong> {{ role }}</p>
				<p><strong>Bio:</strong> {{ bio }}</p>
			</div>
		</div>
    {% endif %}
    
    {% if request.user.username == username %}
        <a href="/profile/form_update/">
            <button type="submit" class="m-4 px-4 py-2 rounded-md bg-blue-500 hover:bg-blue-700 text-white">
                Edit Profile
            </button>
        </a>
    {% endif %}
    
    {% if request.user.username != username and not already_reported %}
        <a href="{% url 'report:report_user' reported_user_id=this_user.id %}">
            <button type="button" class="m-4 px-4 py-2 rounded-md bg-red-500 hover:bg-red-700 text-white">
                Report User 
            </button>
        </a>
        
    {% endif %}

    {% if report_success %}
        <div class="h-screen flex flex-col items-center p-10">
            <!-- Rest of your content -->

            <!-- JavaScript code to display a popup -->
            <script>
                // Check if report_success is true and display a popup message
                window.onload = function() {
                    alert("Report Berhasil");
                };
            </script>
        </div>
    {% endif %}
</div>
{% endblock content %}