backend/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/',include('login.urls')),
    path('community/',include('community.urls')),
    path('profile/',include('profile_user.urls')),
    path('invitation/',include('invitation.urls')),
    path('report/',include('report.urls')),
    path('post/',include('post.urls')),
    path('notification/',include('notification.urls')),
    path('comment/',include('comment.urls')),
]

community/urls.py
from django.urls import path
from community.views import *
from post.views import show_community

app_name = 'community'

urlpatterns = [
    path('', index, name='index'),
    path('search/', search, name='search'),
    path('create/', create_community, name='create_community'),
    # GET community member with member id 
    path('<int:community_id>/member/', get_community_member, name='get_community_member'),
    #path('<int:community_id>/detail/', show_community_detail, name='show_community_detail'),
    # join community
    path('join/', join_community, name='join_community'),
    # send invitation
    path('invite/', send_invitation, name='send_invitation'),
    path('<str:community_name>/', show_community, name='show_community'),
    # show all user
    path('user/<int:community_id>/', show_all_user, name='show_all_user'),
]

post/urls.py
from django.urls import path
from post.views import *

app_name = 'post'

urlpatterns = [
    path('<str:community_name>/<int:id>/', show_post_detail, name='show_post_detail'),
    path('<str:community_name>/create/', create_post, name='create_post'),
    path('<int:post_id>/like/', like_post, name='like_post'),
    path('<int:post_id>/dislike/', dislike_post, name='dislike_post'),
]

profile_user/urls.py
from django.urls import path
from profile_user.views import *

app_name = 'profile_user'

urlpatterns = [
    path('', index, name='index'),
    path('form_update/', show_form_update_profile, name='show_form_update_profile'),
    path('<str:username>/', get_profile_by_username, name='get_profile_by_username'),
    path('update/<str:username>/', update_profile, name='update_profile')
]

community/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Community(models.Model):
    nama_community = models.CharField(max_length=50)
    detail_community = models.TextField()
    leader = models.ForeignKey(User, on_delete=models.CASCADE)
    jumlah_anggota = models.IntegerField()
    jumlah_direport = models.IntegerField(
        default=0,
    )

class Anggota(models.Model):
    community = models.ForeignKey(Community, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

community/views.py
from calendar import calendar
from operator import inv
from django.shortcuts import render
# import csrf_exempt
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from .models import Community, Anggota
from invitation.models import CommunityInvitation, FriendRequest, Invitation
from login.models import UserProfile
from django.contrib.auth.models import User
from django.core import serializers
from rest_framework.parsers import JSONParser
import json
from django.core.serializers.json import DjangoJSONEncoder
from django.contrib.auth.decorators import login_required
# Create your views here.


@login_required(login_url='/auth/login/')
def search(request):
    # check if user is authenticated
    if request.user.is_authenticated:
        # if method is post
        list_community = Community.objects.all()
        list_community_json = serializers.serialize('json', list_community)
        context = {
        "list_community": list_community_json,
        "user": request.user
        }
        return render(request, 'community.html', context)
                         
    else:
        return JsonResponse({"Message":"user belum login"}, status=400)

@login_required(login_url='/auth/login/')
def index(request):
    if request.user.is_authenticated:
        user_communities = Anggota.objects.filter(user=request.user)

        context = {
            'user_communities': user_communities,
            'user': request.user,
            
        }
        return render(request, 'my_community.html', context)
    else:
        return JsonResponse({"Message": "user belum login"}, status=401)
    

    

@csrf_exempt
def create_community(request):
    # check if user is authenticated
    print(request.user.is_authenticated)
    if request.user.is_authenticated:
       # if method is post
        if request.method == "POST":
            data = json.loads(request.body)
            # get data from request
            nama_community = data.get("namaCommunity")
            detail_community = data.get("detail")
            # check if nama_community is already exist, if yes, cannot create community
            if Community.objects.filter(nama_community=nama_community).exists():
                print({"message": "Nama Community sudah ada"})
                return JsonResponse({"message": "Nama Community sudah ada"}, status=400)
            else:
                # create community
                community = Community.objects.create(
                    nama_community=nama_community,
                    detail_community=detail_community,
                    leader=request.user,
                    jumlah_anggota=1,
                )
                # create anggota
                anggota = Anggota.objects.create(
                    community=community,
                    user=request.user
                )
                print({"message": "Community berhasil dibuat",
                                     "nama_community": community.nama_community,
                                     "leader": community.leader.username,
                                     })
                return JsonResponse({"message": "Community berhasil dibuat",
                                     "nama_community": community.nama_community,
                                     "leader": community.leader.username,
                                     }, status=200)
        else:
            return render(request, "create_community.html")
    else:
        return JsonResponse({"message": "User belum login"}, status=400)      

@csrf_exempt   
def join_community(request):
    # check if user is authenticated
    if request.user.is_authenticated:
        # if method is post
        if request.method == "POST":
            data = json.loads(request.body)
            # get nama_community from request
            nama_community = data.get("nama_community")
            # get community
            community = Community.objects.get(nama_community=nama_community)
            # check if user is already in community
            if Anggota.objects.filter(community=community, user=request.user).exists():
                return JsonResponse({"message": "User sudah bergabung dalam community ini"}, status=400)
            else:
                # create anggota
                anggota = Anggota.objects.create(
                    community=community,
                    user=request.user
                )
                # update jumlah anggota
                community.jumlah_anggota += 1
                community.save()
                return JsonResponse({"message": "User berhasil bergabung dalam community ini"}, status=200)
        else:
            return JsonResponse({"message": "Method not allowed"}, status=400)
    else:
        return JsonResponse({"message": "User belum login"}, status=400)

@csrf_exempt
def get_community_member(request, community_id):
    # check if user is authenticated
    if request.user.is_authenticated:
        # get community based on id
        community = Community.objects.get(id=community_id)
        # get all anggota from community
        anggota = Anggota.objects.filter(community=community)
        # get all user from anggota
        user = UserProfile.objects.filter(user__in=anggota.values_list('user', flat=True))
        # return all user
        is_leader = community.leader == request.user
        context = {
            "user": request.user,
            "is_leader": is_leader,
            "community": community,
            "anggota": user
        }
        return render(request, 'community_member.html', context)
    else:
        return JsonResponse({"message": "User belum login"}, status=400)
    

@csrf_exempt
def send_invitation(request):
    # check if user is authenticated
    if request.user.is_authenticated:
        # if method is post
        if request.method == "POST":

            data = json.loads(request.body)
            # get nama_community from request
            nama_community = data.get("nama_community")
            print(nama_community)
            if Community.objects.filter(nama_community=nama_community).exists():
                community = Community.objects.filter(nama_community=nama_community)[0]
                print(community)
                if request.user == community.leader:
                # get receiver from request
                    receiver_name = data.get("receiver")
                    pesan = data.get("pesan")
                # get community
                    community = Community.objects.get(nama_community=nama_community)
                # get receiver
                    receiver = User.objects.get(username=receiver_name)
                # check if user is already in community
                    if Anggota.objects.filter(community=community, user=receiver).exists():
                        return JsonResponse({"message": "User sudah bergabung dalam community ini"}, status=400)
                    elif CommunityInvitation.objects.filter(community=community, receiver=receiver).exists():
                        return JsonResponse({"message": "User sudah mendapat invitation dari community ini"}, status=400)
                    else:
                # create community invitation
                        community_invitation = CommunityInvitation.objects.create(
                            community=community,
                            receiver=receiver,
                            sender=request.user,
                            pesan=pesan,
                            is_responded=False
                        )
                        community_invitation.save()
                        return JsonResponse({"message": "Invitation berhasil dikirim",
                                             "success": True
                                             }, status=200)
                else:
                    print("User bukan leader dari community ini")
                    return JsonResponse({"message": "User bukan leader dari community ini",
                                         "success": False
                                         }, status=400)
            else:
                print("Community tidak ditemukan")
                return JsonResponse({"message": "Community tidak ditemukan",
                                     "success": False
                                     }, status=400)
        else:
            print("Method not allowed")
            return JsonResponse({"message": "Method not allowed",
                                 "success": False 
                                 }, status=400)
    else:
        print("User belum login")
        return JsonResponse({"message": "User belum login"}, status=400)

@csrf_exempt
def show_all_user(request, community_id):
    if request.user.is_authenticated:
            print(request.body)
            community = Community.objects.get(id=community_id)
            community_members = Anggota.objects.filter(community__id=community_id).values_list('user__username', flat=True)
            invited = CommunityInvitation.objects.filter(community__id=community_id).values_list('receiver__username', flat=True)

            list_user = list(UserProfile.objects.exclude(user__username__in=community_members).exclude(user__username__in=invited).values('user__username', 'bio'))
            print(str(list_user))
            # return all user
            context = {
                    "list_user": list_user,
                    "community": community,
                }
            print(context) 
            return render(request, 'all_user.html', context)
    else:
        return JsonResponse({"Message": "user belum login"}, status=401)
    

    

community/templates/all_user.html
{% extends 'base.html' %} 
{% load static %} 
{% block meta %}
<title>Connectify - Invite to Community </title>
{% endblock meta %} 
{% block content %}

<div class="h-screen flex flex-col items-center p-10" style="width: 100%;"> 

	<div class="bg-gray-200 p-6 rounded-lg shadow-md mb-6">

		<div class="input-group">
            <input type="text" id="search-input" class="form-control rounded" placeholder="Search user" aria-label="Search" aria-describedby="search-addon" />
            <button type="button" id="search-button" class="btn rounded-md bg-blue-500 hover:bg-blue-700 text-white" data-mdb-ripple-init>search</button>
          </div>


        <div class="d-flex justify-content-center" id="not-found-message">
        </div>
        <div class="card" id= "results-container" style="width: 100%;">
            
        </div>
	</div>


</div>

{% block scripts %}
{{ list_user|json_script:"listUser" }};
<script>
    var listUser = JSON.parse(document.getElementById('listUser').textContent);
    var resultsContainer = document.getElementById('results-container');
    var notFoundMessage = document.getElementById('not-found-message');
    console.log(listUser);
    
    document.getElementById("search-button").addEventListener('click', function() {
        var searchInput = document.getElementById("search-input").value;

        var results = listUser.filter(function(user) {
            return user.user__username.toLowerCase().includes(searchInput.toLowerCase());
        });

        resultsContainer.innerHTML = '';
        notFoundMessage.innerHTML = '';
        // Create a new card for each result
        if (results.length === 0){
            notFoundMessage.innerHTML += `<p>No results for ${searchInput}</p>`;
        } else { 
            results.forEach(function(result) {
                var card = `
                <div class="row p-3">
                <div class="col-2 d-flex align-items-center justify-content-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                    <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0zm3.292 3.706c-.722-.573-1.675-.875-2.558-.956A4.002 4.002 0 0 1 4.732 9c-.874.08-1.841.383-2.565.965C.956 10.825 0 12.079 0 13.5a.5.5 0 0 0 .5.5h15a.5.5 0 0 0 .5-.5c0-1.422-.956-2.675-2.168-3.794z"/>
                </svg>
                </div>
                    <div class="col-6">
                        <p class="card-title">
                            <strong>
                            ${ result.user__username }
                            </strong>
                        </p>
                        <p class="card-text">${result.bio }</p>
                    </div>

                    
                    <div class="col-4 d-flex align-items-center justify-content-end">
                        <button class="m-1 px-4 py-2 rounded-md bg-blue-500 hover:bg-blue-700 text-white invite-button" type="button" data-username="${ result.user__username }">Invite</button>
                    </div>
                    
                </div>
                `;

                // Add the card to the results container
                resultsContainer.innerHTML += card;
            }
            );
            document.querySelectorAll('.invite-button').forEach(function(button) {
                button.addEventListener('click', function(e) {
                    e.preventDefault();

                    var username = this.getAttribute('data-username');
                    var communityName = '{{ community.nama_community }}';
                    console.log(username, communityName);
                    fetch('/community/invite/', {
                        method: 'POST',
                        body: JSON.stringify({
                            'receiver': username,
                            'nama_community': communityName,
                            'pesan' : "You've been invited to join " + communityName + " community"
                        }),
                        headers: {
                            'Content-Type': 'application/json',
                        }

                    }).then((response) => response.json())
			        .then((data) => {
				        console.log(data);
				        if (data.success) {
                            var url = '/community/user/{{community.id}}';
                            console.log('Redirecting to:', url);
                            window.location.href = url;
				        } else if (data.success === false) {
					        showAlert("error!", "error");
					        
				}
			})
			.catch((error) => {
				console.error("Error:", error);
				showAlert("An error occurred during the update", "error");
			});
                });
            });
        }
    });

</script>
{% endblock scripts %}
{% endblock content %}

community/templates/community.html
{% extends 'base.html' %} 
{% load static %} 
{% block meta %}
<title>Connectify - Community </title>
{% endblock meta %} 
{% block content %}

<div class="h-screen flex flex-col items-center p-10" style="width: 100%;">


	<div class="bg-gray-200 p-6 rounded-lg shadow-md mb-6">

		<div class="input-group">
            <input type="text" id="search-input" class="form-control rounded" placeholder="Search community" aria-label="Search" aria-describedby="search-addon" />
            <button type="button" id="search-button" class="btn rounded-md bg-blue-500 hover:bg-blue-700 text-white" data-mdb-ripple-init>search</button>
          </div>


        <div class="d-flex justify-content-center" id="not-found-message">
        </div>
        <div class="card" id= "results-container" style="width: 100%;">
            
        </div>
	</div>


</div>
{% block scripts %}
<script>
    console.log('{{list_community|escapejs }}');
    var listCommunity = JSON.parse('{{ list_community|escapejs }}');
    var resultsContainer = document.getElementById('results-container');
    var notFoundMessage = document.getElementById('not-found-message');
    console.log(listCommunity);
    
    document.getElementById("search-button").addEventListener('click', function() {
        var searchInput = document.getElementById("search-input").value;

        var results = listCommunity.filter(function(community) {
            return community.fields.nama_community.toLowerCase().includes(searchInput.toLowerCase());
        });

        resultsContainer.innerHTML = '';
        notFoundMessage.innerHTML = '';
        // Create a new card for each result
        if (results.length === 0){
            notFoundMessage.innerHTML += `<p>No results for ${searchInput}</p>`;
        } else { results.forEach(function(result) {
            var card = `
                    <a href="/community/${result.fields.nama_community}/">
                    <div class="card-body">
                    <h5 class="card-title"><strong>${result.fields.nama_community}</strong></h5>
                    <p class="card-text">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-people-fill" viewBox="0 0 16 16" style="display: inline-block; vertical-align: middle;">
                    <path d="M7 14s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1zm4-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6m-5.784 6A2.238 2.238 0 0 1 5 13c0-1.355.68-2.75 1.936-3.72A6.325 6.325 0 0 0 5 9c-4 0-5 3-5 4s1 1 1 1zM4.5 8a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5"/>
                    </svg>
                    <span style="display: inline-block; vertical-align: middle;">${result.fields.jumlah_anggota} Members</span>
                    </p>
                    <p class="card-text">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-info-circle" viewBox="0 0 16 16" style="display: inline-block; vertical-align: middle;">
                        <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16"/>
                        <path d="m8.93 6.588-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533zM9 4.5a1 1 0 1 1-2 0 1 1 0 0 1 2 0"/>
                        </svg> 
                        <span style="display: inline-block; vertical-align: middle;">${result.fields.detail_community.length > 100 ? result.fields.detail_community.substring(0, 100) + '...' : result.fields.detail_community}</span>
                        
                    </p>
                    </div>
                    <a>
                    
                `;

            // Add the card to the results container
                resultsContainer.innerHTML += card;
        });
        }

    });

</script>
{% endblock scripts %}
{% endblock content %}

community/templates/community_member.html
{% extends 'base.html' %} 
{% load static %} 
{% block meta %}
<title>Connectify - Community Member</title>
{% endblock meta %} 
{% block content %}

<div class="h-screen flex flex-col items-center p-10" style="width: 100%;"> 

	<div class="bg-gray-200 p-6 rounded-lg shadow-md mb-6">
        <h5 style="text-align: center; font-size: 2em;">
            {{community.nama_community}} members
        </h5>
        <div class="card" id= "results-container" style="width: 100%;">
            {% for person in anggota %}

            <div class="card-body">
                <div class="row">
                    <div class="col-2 d-flex align-items-center">
                        <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                            <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0zm3.292 3.706c-.722-.573-1.675-.875-2.558-.956A4.002 4.002 0 0 1 4.732 9c-.874.08-1.841.383-2.565.965C.956 10.825 0 12.079 0 13.5a.5.5 0 0 0 .5.5h15a.5.5 0 0 0 .5-.5c0-1.422-.956-2.675-2.168-3.794z"/>
                        </svg>
                    </div>
                    <div class="col-6">
                        <p class="card-title">
                            <strong>
                            {{ person.user }}
                            </strong>
                        </p>
                        <p class="card-text">{{ person.bio }}</p>
                    </div>

                    {% if person.user != user %}
                        <div class="button-wrapper">
                            <button class="m-1 px-4 py-2 rounded-md bg-blue-500 hover:bg-blue-700 text-white invite-button" type="button" data-username="{{ person.user }}">Add Friend</button>
                            <a href="{% url 'profile_user:get_profile_by_username' person.user.username %}" class="profile-link">
                                <button class="m-1 px-4 py-2 rounded-md bg-green-500 hover:bg-green-700 text-white profile-button" type="button">View Profile</button>
                            </a>
                        </div>
                    {% endif %}

                </div>
            </div>
            {% endfor %}
        </div>
	</div>


</div>
{% block scripts %}
<script>
        document.querySelectorAll('.invite-button').forEach(function(button) {
        button.addEventListener('click', function(e) {
            e.preventDefault();

            var username = this.getAttribute('data-username');
            var communityName = '{{ community.nama_community }}';
            console.log(username, communityName);
            fetch('/', {
                method: 'POST',
                body: JSON.stringify({
                    'receiver': username,
                    'community_name': communityName,
                    'pesan' : "You've been invited to join " + communityName + " community"
                }),
                headers: {
                    'Content-Type': 'application/json',
                }
            });
        });
    });
</script>
{% endblock scripts %}
{% endblock content %}

community/templates/create_community.html
{% extends 'base.html' %} {% load static %} {% block meta %}
<title>Connectify - Create Community</title>
<style>
	#updateButton.loading {
		cursor: not-allowed;
		opacity: 0.7;
	}
</style>
<script>
	function createCommunity(event) {
        event.preventDefault();
        const namaCommunity = document.getElementById('community-name').value;
        const detail = document.getElementById('detail').value;
        console.log(namaCommunity);
        fetch('/community/create/', {
            method: 'POST',
            headers: {
            'Content-Type': 'application/json',
            },
            body: JSON.stringify({namaCommunity, detail}),
        })
        .then(response => response.json().then(data => ({status: response.status, body: data})))
        .then(data => {
        if (data.status === 200) {
            showAlert(data.body.message, "success");
            window.location.href = '/community';
        } else {
            showAlert(data.body.message, "error");
        }
})
.catch(error => {
    showAlert(error.toString(), "error");
});
    }
	function showAlert(message, type) {
		Toastify({
			text: message,
			duration: 3000,
			gravity: "bottom",
			position: "right",
			backgroundColor: type === "success" ? "#4CAF50" : "#F44336",
		}).showToast();
	}
</script>
{% endblock meta %} {% block content %}
<div class="min-h-screen flex flex-col items-center p-10">
	<a href="/community" class="flex items-center mb-4 text-blue-500 hover:text-blue-700">
		<i class="fa fa-angle-double-left" style="font-size: 24px"></i>
		<p class="text-sm">&nbspBack</p>
	</a>

	<form onsubmit="createCommunity(event)" class="max-w-md w-full">
		<div class="bg-white p-6 rounded-lg shadow-md mb-6">
			<h1 class="text-3xl font-bold mb-5">Create New Community</h1>
			<div class="mb-4">
				<label for="community-name" class="block text-gray-700 text-sm font-bold mb-2">Name</label>
				<input
					id="community-name"
					type="text"
					placeholder="community Name"
					required
					class="w-full px-4 py-2 rounded-md border-2 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
				/>
			</div>

			<div class="mb-4">
				<label for="detail" class="block text-gray-700 text-sm font-bold mb-2">Detail</label>
				<textarea
					id="detail"
					placeholder="community detail"
					required
					class="w-full rounded border-2 py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
				></textarea>
			</div>

			<button
				id="updateButton"
				type="submit"
				class="w-full px-4 py-2 rounded-md bg-blue-500 hover:bg-blue-700 text-white"
			>
				Create!
			</button>
		</div>
	</form>
</div>

{% endblock content %}
   

community/templates/my_community.html
{% extends 'base.html' %} {% load static %} {% block meta %}
<title>Connectify - My Communities</title>
<style>
	#updateButton.loading {
		cursor: not-allowed;
		opacity: 0.7;
	}
</style>
{% endblock meta %} {% block content %}
<div class="min-h-screen flex flex-col items-center p-10">
    <div class="bg-gray-200 p-6 rounded-lg shadow-md mb-6" style="width: 40%;">
        <h5 style="text-align: center; font-size: 2em;">
            <strong>
                Your Communities
            </strong>
        </h5>
        <div class="d-flex justify-content-center">
            <a href="/community/search/">
                <button type="submit" class="m-1 px-4 py-2 rounded-md bg-blue-500 hover:bg-blue-700 text-white">
                    Search Community
                </button>
            </a>
            <a href="/community/create/">
                <button type="submit" class="m-1 px-4 py-2 rounded-md bg-blue-500 hover:bg-blue-700 text-white">
                    Create Community
                </button>
            </a>
        </div>
        <div class="card" id= "results-container" style="width: 100%;">
            {% for anggota in user_communities %}
            <a href="/community/{{anggota.community.nama_community}}/">
                <div class="card-body">
                <h5 class="card-title"><strong>{{anggota.community.nama_community}}</strong></h5>
                <p class="card-text">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-people-fill" viewBox="0 0 16 16" style="display: inline-block; vertical-align: middle;">
                <path d="M7 14s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1zm4-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6m-5.784 6A2.238 2.238 0 0 1 5 13c0-1.355.68-2.75 1.936-3.72A6.325 6.325 0 0 0 5 9c-4 0-5 3-5 4s1 1 1 1zM4.5 8a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5"/>
                </svg>
                <span style="display: inline-block; vertical-align: middle;">{{anggota.community.jumlah_anggota}} Members</span>
                </p>
                <p class="card-text">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-info-circle" viewBox="0 0 16 16" style="display: inline-block; vertical-align: middle;">
                    <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16"/>
                    <path d="m8.93 6.588-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533zM9 4.5a1 1 0 1 1-2 0 1 1 0 0 1 2 0"/>
                    </svg> 
                    <span style="display: inline-block; vertical-align: middle;">{{ anggota.community.detail_community|truncatechars:100 }}</span>
                </p>
                </div>
                <a>
        {% empty %}
        <p>You have not joined any communities yet.</p>
        {% endfor %}
        </div>
    </div>
</div>

{% endblock content %}
   